name: accounting
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  intl: ^0.20.2
  go_router: ^14.8.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  injectable: ^2.3.2
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  internet_connection_checker: ^3.0.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  fluttertoast: ^8.2.12
  loader_overlay: ^5.0.0
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  integration_test:
    sdk: flutter
  custom_lint:
  flutter_gen_runner:
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/